---
- name: Set ConfigMap Logstash on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes  

  tasks:

   - name: Creating a file pipeline.yml Logstash 
     copy:
      dest: "/k8s/pipelines.yml"
      content: |
        - pipeline.id: {{ config_1 }}
          path.config: "/application/logstash/{{ config_1 }}.cgf"
        - pipeline.id: {{ config_2 }}
          path.config: "/application/logstash/{{ config_2 }}.cfg"
        - pipeline.id: {{ config_3 }}
          path.config: "/application/logstash/{{ config_3 }}.cfg"  
      
   - name: Run Kubectl delete Configmap 
     command: kubectl delete cm multipleconfig
     register: configmap  
      
   - name: Run Kubectl Cria Configmap 
     command: kubectl create cm multipleconfig --from-file=/k8s/pipelines.yml 
     register: configmap
