---
- name: Set ConfigMap Logstash on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes

  tasks:
  
    - name: 'Export namespace'
      command: export NS={{ NS }}

    - name: 'Run Kubectl config Context'
      command: kubectl config set-context --current --namespace="{{ NS }}"

    - name: 'Start Trigger Pipeline gitlab'
      command: curl --request POST --form token=9981c9b238f3555dde7d1d6d9d164f --form ref=ansible-set-propetie --form "variables[NS]="{{ NS }}"" --form "variables["{{ msvariable }}"]={{ propertie }}" "https://gitlab.corp.sigga.com/api/v4/projects/189/trigger/pipeline"
