---
- name: Set ConfigMap on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes

  tasks:
    
    - name: Set Facts
      set_fact:
        path: "{{ lookup('file',playbook_dir file=configmap.yaml }}"

    - name: Set Variables
     command: envsubst < {{path}}
     register: k8s_var_results

    - name: Run Kubectl config Context
     command: kubectl config use-context $KUBE_CTX
     register: k8s_config_context

   - name: Update Configmap
     command: kubectl apply -f {{path}} -n $NS
     register: configmap
