---
- name: Set ConfigMap on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes

  tasks:
    
    - name: Set Facts
      set_fact:
        path: "{{ lookup('file',playbook_dir file=configmap.yaml }}"
        
     - name: Export namespace
     command: export {{NS}}
     register: exportvars   

    - name: Run Kubectl config Context
     command: kubectl config set-context --current --namespace={{NS}}
     register: k8s_config_context
     
     - name: Export var
     command: export {{variable}}
     register: exportvars
     
   - name: Update Configmap
     command: envsubst < {{path}} | kubectl apply -f -
     register: setconfigmap
