---
- name: Set ConfigMap Logstash on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes  

  tasks:

   - name: Creating a file with content
     copy:
      dest: "/k8s/pipelines.yml"
      content: |
        line 01
        line 02
      
    #- name: Run Kubectl delete Configmap 
      #command: kubectl delete cm multipleconfig
      #register: configmap  
      
    #- name: Run Kubectl Cria Configmap 
      #command: kubectl apply cm multipleconfig --from-file=pipelines.yml --from-file={{ config_1 }} --from-file={{ config_2 }}
      #register: configmap
  
  
    
     
