---
- name: Set ConfigMap Logstash on k8s
  hosts: local
  #remote_user: root
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes  

  tasks:

    #- name: Run Kubectl Remote host
      #command: kubectl create cm multipleconfig --from-file=pipelines.yml --from-file={{ config_1 }} --from-file={{ config_2 }}
      #register: configmap
      
    - name: Run Kubectl Get pods
      command: kubectl get pods
      register: pods
  
  
    
     
