---
- name: Set ConfigMap Logstash on k8s
  hosts: local
  gather_facts: yes
  vars_files:
    - kubectl_vars.yml
  collections:
    - community.kubernetes  

  tasks:

    #- name: Run Kubectl Remote host
      #command: kubectl create cm multipleconfig --from-file=pipelines.yml --from-file={{ config_1 }} --from-file={{ config_2 }}
      #register: configmap
      
    - name: Run Kubectl Cria Configmap 
      command: kubectl create cm multipleconfig
      register: configmap
  
  
    
     
